app = "playlink-api"
primary_region = "cdg"

[build]
  builder = "paketobuildpacks"

[[services]]
  internal_port = 3002
  protocol = "tcp"
  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
