import { config } from "dotenv";
import { resolve } from "path";
config({ path: resolve(process.cwd(), ".env.local") });
import { PrismaClient } from "@prisma/client";
import { newGames, dilemmeGame, defaultRules } from "./seed-new-games";

const prisma = new PrismaClient();

const seedData = [
  {
    name: "Action ou Vérité",
    slug: "action-ou-verite",
    description: "Le classique revisité — action ou vérité, à toi de choisir !",
    icon: "🎯",
    colorMain: "#D4537E",
    colorSecondary: "#ED93B1",
    order: 0,
    categories: [
      {
        name: "Vérités Classique",
        slug: "verites-classique",
        icon: "😄",
        description: "Drôle et léger",
        order: 0,
        cards: [
          "Quel est le mensonge le plus blanc que tu aies dit cette semaine ?",
          "Quel est ton souvenir le plus embarrassant au lycée ?",
          "C'est quoi ta chanson honte secrète que tu écoutes en boucle ?",
          "Tu as un doudou secret ou un objet auquel tu tiens trop ?",
          "Ton pire rendez-vous galant en une phrase ?",
          "Quelle application t'a fait perdre le plus de temps cette année ?",
          "Quelle célébrité tu croiserais dans la rue sans la reconnaître ?",
          "Ton emoji le plus utilisé et pourquoi ?",
          "Tu préfères être à l'heure mais stressé ou en retard mais zen ?",
          "Quel est ton hobby secret qu'on ne connaît pas ?",
          "Qu'est-ce que tu fais seul(e) dont tu aurais honte ?",
          "C'est quoi ta plus grosse gaffe ?",
          "Quelle appli utilises-tu beaucoup trop, et pour quoi faire exactement ?",
          "Quel petit détail chez quelqu'un te fait craquer instantanément ?",
          "L'objet le plus improbable que tu as chez toi ?",
          "Quel son ou bruit te rend fou involontairement ?",
          "Tu as un talent que personne ne connaît ?",
          "Quel serait ton nom de rappeur ou de super-héros ?",
          "Si tu avais une publicité qui te suivait partout, quel serait le slogan ?",
          "Quel genre d'enfant étais-tu ?",
          "Tu as déjà parlé à quelqu'un par texto en croyant écrire à quelqu'un d'autre ?",
          "Un souvenir de vacances qui te rends nostalgique juste en y pensant ?",
          "C'est quoi le truc que tu dis que tu vas faire mais ne fais jamais ?",
          "Qu'est-ce que tu aimerais beaucoup faire tout de suite ?",
          "Si tu devais porter le même vêtement pendant un an, ce serait lequel ?",
          "Quelle est la chose la plus bizarre que tu aies mangée ?",
          "Qu'est-ce que tu aimerais que les gens comprennent mieux à ton sujet ?",
          "C'est quoi ta couleur préférée ?",
          "Quel est ta musique du moment ?",
          "Quel est ta série/films préféré ?",
          "C'est quoi ta maison de rêve ?",
          "Tu aimes plutôt les chats ou les chiens ?",
          "Plutôt café ou thé ?",
          "Plutôt plage ou montagne pour vacances ?",
          "Plutôt cinema ou séries ?",
        ],
      },
      {
        name: "Vérités cruch",
        slug: "verites-cruch",
        icon: "❤️",
        description: "Flirteur, confessions amoureuses",
        order: 1,
        cards: [
          "T'as un crush sur quelqu'un ici ?",
          "C'est quoi ton type idéal ?",
          "T'as déjà eu un moment avec quelqu'un du groupe ?",
          "Quel est le plus beau compliment qu'on t'ait fait ?",
          "T'as déjà dit 'Je t'aime' sans vraiment le penser ?",
          "Quel est ton plus grand regret amoureux ?",
          "Ton pire plan drague, raconte la story.",
          "Quel moment avec quelqu'un te rends nostalgique ?",
          "C'est qui dans ce groupe que tu appellerais en premier en cas d'urgence amoureuse ?",
          "As-tu déjà couché le premier soir ? Qu'est-ce qui a pesé dans la décision ?",
          "As-tu déjà envoyé un « tu dors ? » à 2h pour revoir quelqu'un ? Qu'est-il arrivé ensuite ?",
          "Quel est le plus beau souvenir amoureux que tu as ?",
          "T'as une personne ici que tu trouves particulièrement attirant ?",
          "Est-ce qu'il y a quelqu'un d'ici dont tu aimerais tester la chimie ?",
          "Combien de personnes as-tu réellement aimées dans ta vie ?",
          "Comment et pourquoi tes anciennes relations se sont terminées ? Qu'as-tu appris ?",
          "Qu'est-ce qui n'a pas marché dans tes précédentes relations ?",
          "Tu as un ex préféré ?",
          "Qui ici selon toi pourrait être un bon rendez-vous ?",
          "Quels sont tes red flags dans une relation ?",
          "Quels sont tes green flags dans une relation ?",
          "Quel est le choix le plus courageux que tu aies fait récemment en amour ?",
          "Décrit ton rendez-vous idéal.",
          "Le lieu le plus imprévu où tu as eu un rencard sympa ?",
          "Quel est le plus gros compromis que tu as dû faire dans une relation ?",
          "Comment tu vois ta relation idéale dans 5 ans ?",
          "Quels sont les signaux d'alerte qui te font fuir une relation ?",
          "Comment tu célèbres les anniversaires ou jalons importants ?",
          "As-tu peur de l'abandon ? Pourquoi ?",
          "Comment tu exprimes l'amour : par des paroles, des actes, du temps, des cadeaux ?",
          "Quel est le moment où tu as vraiment senti que tu aimais quelqu'un ?",
          "Peux-tu être heureux seul ou as-tu besoin d'une relation pour être complet ?",
          "Comment tu gères les différences fondamentales avec quelqu'un que tu aimes ?",
          "As-tu déjà rompu pour des raisons qui te paraissent stupides rétrospectivement ?",
          "Quel est le rôle de la routine dans une relation selon toi ?",
          "Comment tu ferais pour reconquérir quelqu'un que tu as perdu ?",
        ],
      },
      {
        name: "Actions classique",
        slug: "actions-classique",
        icon: "🎈",
        description: "Défis marrants et léger",
        order: 2,
        cards: [
          "Imite la voix de la dernière personne à qui tu as parlé.",
          "Fais le tour de la pièce en dansant sans musique.",
          "Dis 'je t'aime' à la personne à ta gauche avec le plus grand sérieux possible.",
          "Poste une photo de toi maintenant sur tes réseaux sans filtre.",
          "Chante la première chanson qui te passe par la tête pendant 30 secondes.",
          "Fais 10 pompes maintenant.",
          "Parle en chuchotant pour le prochain tour.",
          "Dessine un portrait de la personne en face de toi en 30 secondes.",
          "Appelle quelqu'un au hasard dans tes contacts et dis-lui une blague pourrie.",
          "Envoie un message vocal à quelqu'un que tu n'as pas contacté depuis 6 mois.",
          "Fais le meilleur accent étranger pendant 30 secondes.",
          "Fais une grimace la plus drôle possible.",
          "Raconte une blague qui t'a fait rire récemment.",
          "Fais le bruit d'un animal pendant 10 secondes.",
          "Danse comme si personne ne regarde pendant 30 secondes.",
          "Fais semblant d'être un présentateur météo pendant 1 minute.",
          "Parle avec un accent étranger pendant tout le prochain round.",
          "Imite la personne de ton choix dans le groupe jusqu'à ce qu'on la devine.",
          "Demande aux autres de te donner un défi physique original.",
          "Explique un concept compliqué comme si tu l'expliquais à un enfant de 5 ans.",
          "Récite l'alphabet à l'envers le plus vite possible.",
          "Décris quelqu'un du groupe sans dire son nom jusqu'à ce qu'on le devine.",
          "Fais un monologue dramatique sur quelque chose d'ordinaire.",
          "Mime un travail jusqu'à ce qu'on le devine.",
          "Fais une pub pour un produit imaginaire de 30 secondes.",
          "Parle avec la voix la plus grave ou aiguë possible pendant une minute.",
          "Fais un strip-tease symbolique sur la musique mentale de ton choix.",
          "Serre la main de quelqu'un comme si tu rencontrais le PDG du monde.",
          "Marche comme un pingouin pendant 1 minute.",
          "Fais une révérence exagérée à chaque personne du groupe.",
          "Demande à quelqu'un de te donner un surnom basé sur ton apparence.",
          "Crie le plus fort possible 'Je suis fabulous'.",
          "Fais une danse ridicule pendant 30 secondes.",
          "Imite quelqu'un du groupe jusqu'à ce qu'on te devienne.",
          "Donne un surnom à chaque personne du groupe.",
          "Raconte une histoire embarrassante sur toi en 30 secondes.",
        ],
      },
      {
        name: "Actions Cruch",
        slug: "actions-cruch",
        icon: "🔥",
        description: "Pour ceux qui veulent pimenter la soirée, flirter, confessions amoureuses, attirance",
        order: 3,
        cards: [
          "Appelle quelqu'un au hasard dans tes contacts et chante-lui Joyeux Anniversaire.",
          "Écris un message d'amour à la personne de ton choix dans le groupe et lis-le à voix haute.",
          "Prends une vidéo de toi en train de faire ton meilleur déhanché et envoie-la.",
          "Laisse la personne à ta droite choisir ta prochaine photo de profil pendant une journée.",
          "Fais une déclaration à quelqu'un du groupe comme si c'était une scène de film.",
          "Poste un selfie avec la légende 'Bonne nuit' même s'il est 15h.",
          "Parle avec un accent étranger pendant tout le prochain round.",
          "Imite la personne de ton choix dans le groupe jusqu'à ce qu'on la devine.",
          "Demande aux autres de te donner un défi physique original.",
          "Donne un compliment sincère à chaque personne du groupe.",
          "Appelle quelqu'un et dis-lui que tu l'aimes.",
          "Envoie un message à ton ex maintenant.",
          "Poste une photo de toi sans filtre sur tes réseaux.",
          "Fais un zouk d'une minute avec la personne de ton choix.",
          "Danse un slow avec la personne que le groupe trouve la plus rayonnante.",
          "Tu as 1 minute pour séduire la personne qui t'attire le plus ici.",
          "Propose un bisou rapide à la personne de ton choix, uniquement si elle en a vraiment envie.",
          "Kiss challenge : rapprochez vos lèvres très près sans vous toucher, et restez ainsi 5 secondes.",
          "Regardez-vous en silence pendant 10 secondes.",
          "Choisis quelqu'un et échangez un compliment précis.",
          "Mime ta position préférée au lit.",
          "Demande à quelqu'un ici de te donner un surnom.",
          "Envoie un message vocal sexy à quelqu'un du groupe.",
          "Donne un massage de 30 secondes à la personne à ta gauche.",
          "Flirte ouvertement avec quelqu'un du groupe pendant 1 minute.",
          "Dis à quelqu'un ici ce que tu trouves le plus attirant chez lui.",
          "Prends la main de quelqu'un et donne-la un baiser.",
          "Sensualise ta voix et dis quelque chose de simple de manière séxy.",
          "Fais un clin d'œil séducteur à chaque personne du groupe.",
          "Murmure quelque chose à l'oreille de quelqu'un du groupe.",
          "Donne à quelqu'un un compliment physique vraiment sincère.",
          "Danse sensiblement avec quelqu'un du groupe pendant 30 secondes.",
          "Appelle quelqu'un et dis-lui une phrase flirtieuse.",
          "Fais un striptease symbolique pour quelqu'un du groupe.",
          "Propose un baiser sur les joues à quelqu'un en le regardant dans les yeux.",
        ],
      },
    ],
  },
  {
    name: "Icebreaker",
    slug: "icebreaker",
    description: "Brisez la glace — des questions pour apprendre à vraiment vous connaître.",
    icon: "🧊",
    colorMain: "#5B8DBE",
    colorSecondary: "#7BA3D1",
    order: 1,
    categories: [
      {
        name: "Pour se découvrir",
        slug: "se-decouvrir",
        icon: "👋",
        description: "Questions pour apprendre à se connaître",
        order: 0,
        cards: [
          "Si tu étais un animal, lequel serais-tu et pourquoi ?",
          "Quel est ton plus beau souvenir ?",
          "C'est quoi ton endroit préféré dans le monde entier ?",
          "Quel est l'objet que tu as depuis le plus longtemps et auquel tu tiens ?",
          "Ton livre, film ou musique que tu voudrais que tout le monde découvre ?",
          "Si tu devais manger le même repas pendant un mois, ce serait quoi ?",
          "C'est quoi ta chanson honte secrète que tu écoutes en boucle ?",
          "Tu préfères être à l'heure mais stressé ou en retard mais zen ?",
          "T'es plus du matin ou de la nuit ?",
          "Tu préfères avoir des mains à la place des pieds ou l'inverse ?",
          "Si tu pouvais téléporter n'importe où pour 1 heure maintenant, où irais-tu ?",
          "Quel emoji te représente le mieux en ce moment ?",
          "Quel serait ton job dans un monde médiéval fantastique ?",
          "C'est quoi ton niveau d'adulte responsable de 1 à 10 ?",
          "Tu as un doudou secret ou un objet auquel tu tiens trop ?",
          "Quel son ou bruit te rend fou involontairement ?",
          "Tu as un talent que personne ne connaît ?",
          "Tu as une phobie ? Laquelle ?",
          "L'objet le plus improbable que tu as chez toi ?",
          "Si tu avais une publicité qui te suivait partout, quel serait le slogan ?",
          "Quelle est ta routine du matin idéale ?",
          "C'est quoi ta journée type idéale ?",
          "Quel serait ton nom de rappeur ou de super-héros ?",
          "Quelle est la dernière chose qui t'a vraiment fait rire aux larmes ?",
          "Qu'est-ce qui te met instantanément de bonne humeur ?",
          "Quel petit détail chez quelqu'un te fait craquer instantanément ?",
          "Quel est ton plus grand rêve ?",
          "Tu as des objectifs dans la vie ? Lesquels ?",
          "Quels sont tes objectifs à court et long termes ?",
          "Comment tu te vois dans 5 ans ? Et dans 10 ans ?",
          "Tu as des destinations de rêve ? Lesquelles ?",
          "Où as-tu déjà voyagé ?",
          "Est-ce que tu aimes voyager ?",
          "Top 3 des villes européennes où tu partirais en city-break ?",
          "Quel est ton plus beau souvenir de voyage ?",
          "Tu as une passion ? Laquelle ?",
          "Quel métier tu voulais faire enfant ?",
          "Comment tu vois ta carrière ?",
          "C'est quoi ton ambition secrète que tu n'oses pas toujours dire ?",
          "Est-ce que tu peux changer de pays par amour ?",
          "Comment tu vois ton avenir professionnel ?",
          "Qu'est-ce qui te donne de l'énergie vs ce qui t'en prend ?",
          "Dans quel(s) pays et type d'habitation aimerais-tu vivre ?",
          "Quel est ton rapport à tes origines et à ta culture ?",
          "Comment te présenterais-tu au monde si tu n'avais peur de rien ?",
          "Quel genre d'enfant étais-tu ?",
        ],
      },
      {
        name: "Cœur à Cœur",
        slug: "coeur-coeur",
        icon: "💬",
        description: "Émotions, amitié, les questions qui comptent",
        order: 2,
        cards: [
          "Qu'est-ce qui te rend vraiment heureux dans ta vie en ce moment ?",
          "C'est quand la dernière fois que tu as vraiment été heureux ? Pourquoi ?",
          "C'est quand la dernière fois que tu as vraiment été triste ? Pourquoi ?",
          "C'est quoi ta plus grande peur que tu n'avoues jamais ?",
          "C'est quoi pour toi le signe d'une vraie amitié ?",
          "C'est quoi l'amitié pour toi et pourquoi ?",
          "L'amitié peut-elle vraiment survivre à une grande trahison ?",
          "Tu crois en l'amitié fille/garçon ?",
          "On peut vraiment rester ami avec un ex ?",
          "Mieux vaut une seule amitié profonde ou 10 amitiés légères ?",
          "Qu'est-ce que tes amis pensent de toi ?",
          "Qu'est-ce que tu as essayé de nouveau cette année ?",
          "C'est quoi ton mood du moment ?",
          "Dans un groupe, quel rôle tu prends naturellement en soirée ?",
          "Dis-moi quelque chose que tu as remarqué chez les personnes ici.",
          "Quel est ton rapport avec ta famille ?",
          "Quel est ta relation avec ta famille ?",
          "Décrit ta relation avec tes parents.",
          "Quel surnom improbable t'est resté, et d'où vient-il ?",
          "Que penses-tu de l'éducation qu'on t'a donnée ?",
          "Est-ce que tu penses avoir grandi dans le chaos ou dans l'amour ?",
          "Tu veux des enfants ? Pourquoi ? Si tu en as, pourquoi tu en voulais ?",
          "Comment tu vois l'éducation de tes enfants ?",
          "Quel est ton rapport avec la solitude ?",
          "Qu'est-ce qui te manque le plus de ton enfance ?",
          "Quelle est la plus belle chose que quelqu'un ait faite pour toi ?",
          "Quelle est la pire chose que quelqu'un t'ait faite ?",
          "C'est quoi pour toi l'amour ?",
          "C'est quoi un homme pour toi ?",
          "C'est quoi une femme pour toi ?",
          "Quel est ta vision du couple ?",
          "Est-ce que tu crois en l'amour à vie ça existe ?",
          "L'amour au premier regard existe vraiment ?",
          "Est-ce que tu veux te marier ?",
          "Le mariage est-il dépassé ?",
          "Comment tu veux recevoir de l'affection ?",
          "Aimes-tu les signes physiques d'affection ? Si oui lesquels ? Si non pourquoi ?",
          "C'est quoi la chose qui t'attires le mieux chez quelqu'un ?",
          "Comment est-ce que tu pourrais être un meilleur partenaire ?",
          "Quel est ton rapport avec l'engagement dans la vie en général ?",
          "Qu'est-ce que l'engagement pour toi ?",
        ],
      },
      {
        name: "Deep Talk",
        slug: "deep-talk",
        icon: "🌙",
        description: "Questions pour des conversations profondes",
        order: 1,
        cards: [
          "Qu'est-ce qui te fait peur quand tu y penses vraiment ?",
          "Comment tu gères ton stress ?",
          "Comment tu gères tes émotions ?",
          "Comment tu prends soin de toi ?",
          "Est-ce que tu as confiance en toi ?",
          "Est-ce que tu as des insécurités ?",
          "Quel est ton avis sur les thérapies ?",
          "Est-ce que tu as des antécédents médicaux ?",
          "Est-ce que tu as des maladies ou un handicap ?",
          "Est-ce que tu as déjà eu des addictions ?",
          "Est-ce que tu as déjà été en dépression ou en deuil ?",
          "Vers qui est-ce que tu te tournes quand ça ne va pas ?",
          "Quelle est la plus grande preuve de résilience que tu aies donnée à toi-même ?",
          "Quel est le geste d'amitié ou d'amour qui t'a le plus touché ?",
          "Quelle est la plus grande vérité que tu as acceptée sur toi-même ?",
          "Quelle vérité sur toi-même tu refuses encore d'accepter ?",
          "Tu te considères comme une bonne personne ? Pourquoi ?",
          "Est-ce que le toi d'il y a 5 ans serait fier de toi aujourd'hui ?",
          "Quel conseil tu donnerais au toi enfant ?",
          "Le meilleur conseil qu'on t'ait donné ?",
          "C'est quand la dernière fois que tu as pleuré et pourquoi ?",
          "Te sens-tu accompli ? Pourquoi ?",
          "Qu'effacerais-tu de ton passé si tu le pouvais ?",
          "Dans quel état est ton cœur en ce moment ?",
          "As-tu peur de la mort ?",
          "Qu'est-ce qui te rendrait heureux tout de suite ?",
          "Raconte-moi le moment le plus gênant de ta vie ?",
          "Quel est ton plus grand échec ? Ta plus grande réussite ?",
          "Quel est le moment où tu as été le plus fier de toi ?",
          "Quelle est la chose la plus folle que tu aies faite dans ta vie ?",
          "Le bonheur s'apprend ou c'est inné ?",
          "L'amour s'apprend ou c'est inné ?",
          "Si tu pouvais lire les pensées des gens, le ferais-tu même si c'est douloureux ?",
          "Mieux vaut une longue vie ordinaire ou une vie courte mais intense ?",
          "Préfères-tu connaître la date de ta mort ou être surpris ?",
          "Si tu pouvais tout recommencer à 18 ans avec ta mémoire actuelle, tu le ferais ?",
          "Si les robots faisaient tout le travail physique, serions-nous plus heureux ?",
          "Vivons-nous pour nous-mêmes ou pour avoir un impact sur les autres ?",
          "La conscience existe-t-elle vraiment ou c'est juste du déterminisme ?",
          "Peut-on avoir une connexion profonde avec quelqu'un en peu de temps ?",
          "Peut-on vraiment changer fondamentalement en tant que personne ?",
        ],
      },
    ],
  },
  {
    name: "Dégât-Débat",
    slug: "degat-debat",
    description: "Les questions qui divisent — choisissez votre camp et défendez-le !",
    icon: "⚡",
    colorMain: "#D97706",
    colorSecondary: "#F59E0B",
    order: 2,
    categories: [
      {
        name: "Société",
        slug: "societe",
        icon: "🌍",
        description: "Les grands débats de notre époque",
        order: 0,
        cards: [
          "Les réseaux sociaux font-ils plus de bien que de mal à notre société ?",
          "Faut-il interdire les voitures dans les centres-villes ?",
          "L'école devrait enseigner la gestion des émotions autant que les maths ?",
          "Les influenceurs ont-ils une responsabilité morale envers leur audience ?",
          "Internet nous rend-il plus intelligents ou plus paresseux ?",
          "Le véganisme devrait-il être encouragé par l'État ?",
          "La semaine de 4 jours devrait être la norme partout ?",
          "Devrait-on obligatoirement voter à partir de 16 ans ?",
          "Faut-il légaliser toutes les drogues douces ?",
          "Les services de santé doivent-ils être entièrement gratuits ?",
          "Faut-il rendre obligatoire le service militaire ou civil ?",
          "La démocratie est-elle toujours le meilleur système politique ?",
          "Les entreprises devraient-elles être responsables juridiquement des impacts environnementaux ?",
          "Les influenceurs devraient-ils être soumis aux mêmes règles que les journalistes ?",
          "Faut-il limiter l'exploitation de ressources naturelles ?",
          "Les musées occidentaux devraient-ils restituer toutes les œuvres volées pendant la colonisation ?",
          "Les robots devraient-ils pouvoir remplacer totalement certains métiers humains ?",
          "Faut-il interdire les deepfakes même à des fins artistiques ?",
          "L'éducation sexuelle devrait-elle être plus explicite et commencée plus tôt ?",
          "Faut-il rendre obligatoire l'enseignement de la politique et de l'économie dès le collège ?",
          "Faut-il privatiser tous les services publics ?",
          "L'immigration est-elle une chance ou un problème ?",
          "Faut-il interdire les partis politiques extrémistes ?",
          "Les manifestations violentes sont-elles justifiées ?",
          "La peine de mort devrait-elle être rétablie ?",
          "Faut-il instaurer un revenu universel ?",
          "Le vote devrait-il être obligatoire ?",
          "Les réseaux sociaux sont-ils un danger pour la démocratie ?",
          "La surveillance de masse est-elle acceptable pour la sécurité ?",
          "Faut-il donner le droit de vote dès 16 ans ?",
          "Les milliardaires devraient-ils être plafonnés en fortune ?",
          "Faut-il limiter la liberté d'expression pour éviter les discours haineux ?",
          "Le télétravail total est-il meilleur pour la productivité ?",
          "L'intelligence artificielle peut-elle vraiment être créative ?",
          "Faut-il supprimer l'anonymat en ligne pour lutter contre le harcèlement ?",
          "Faut-il dévoiler systématiquement le casier judiciaire d'un candidat politique ?",
          "La génération actuelle est-elle foirée ?",
          "La prochaine génération est-elle condamnée à l'échec ?",
        ],
      },
      {
        name: "Relations et Amour",
        slug: "relations-amour",
        icon: "❤️",
        description: "Opinions sur le couple, l'amitié, love, les relations",
        order: 1,
        cards: [
          "L'amitié peut-elle vraiment survivre à une grande trahison ?",
          "On peut vraiment rester ami avec un ex ?",
          "Les relations ouvertes peuvent-elles vraiment marcher ?",
          "Peut-on pardonner une infidélité ?",
          "Faut-il tout dire en couple ?",
          "Faut-il dire à quelqu'un qu'on a déjà été infidèle, même si c'est du passé ?",
          "Un couple peut-il survivre sans relations sexuelles ?",
          "Les couples doivent-ils partager toutes leurs dépenses à parts égales ?",
          "Les couples devraient-ils tout partager sur leur passé sexuel ?",
          "Faut-il absolument être attiré sexuellement par quelqu'un pour rester ensemble ?",
          "Les couples devraient-ils planifier autant leur vie amoureuse que leur carrière ?",
          "L'amour à distance peut-il vraiment fonctionner ?",
          "Quel est ton rapport à la monogamie ?",
          "Où commence la tromperie ?",
          "Pour ou contre partager les codes de ton téléphone en couple ?",
          "Pour ou contre partager la localisation en couple ?",
          "Peut-on échanger les mots de passe en couple ?",
          "Est-ce que toute vérité est bonne à dire ?",
          "Accepterais-tu que quelqu'un réalise un fantasme avec quelqu'un d'autre ?",
          "Un fantasme non réalisé peut-il mettre en danger une relation ?",
          "La compatibilité sexuelle est-elle plus importante que la compatibilité émotionnelle ?",
          "Comment est-ce que tu répartis les dépenses dans un couple ?",
          "Comment est-ce que tu répartis les charges dans un couple ?",
          "Est-ce que tu es pour que ta femme ou ton mari travaille ?",
          "Quel est ton rapport avec l'argent dans une relation ?",
          "La jalousie dans un couple est-elle normale ou toxique ?",
          "Est-ce que tu es jaloux ou possessif ?",
          "Pour ou contre garder les cadeaux de ses ex ?",
          "Un avis sur la dot ?",
          "Comment tu gères les conflits ?",
          "Qu'est-ce que tu cherches vraiment dans une relation ?",
          "Crois-tu qu'on peut aimer deux personnes en même temps ?",
          "Qu'est-ce qu'une relation réussie pour toi ?",
          "Quel est ton plus beau souvenir avec quelqu'un du groupe ?",
          "Qu'est-ce que tu aimerais tester ou faire avec quelqu'un ici ?",
          "Est-ce qu'il y a quelque chose que tu as toujours voulu dire à quelqu'un ici ?",
          "Est-ce que le coup de foudre existe ?",
          "C'est à l'homme de payer au premier rendez-vous ?",
          "Après 2-3 ans de relation, un homme doit-il obligatoirement demander la femme en mariage ?",
          "L'amitié homme-femme existe ?",
          "L'amour s'arrête-t-il après le mariage ?",
          "Une relation à distance peut-elle durer ?",
          "L'amour est-il plus important que le respect dans une relation ?",
        ],
      },
      {
        name: "Éthique et Morale",
        slug: "ethique-morale",
        icon: "🤔",
        description: "Dilemmes de conscience, valeurs",
        order: 2,
        cards: [
          "Mentir pour protéger un proche, est-ce acceptable ?",
          "Peut-on sacrifier une vie pour en sauver plusieurs ?",
          "La torture est-elle justifiée pour sauver des vies ?",
          "Accepterais-tu de trahir un secret si cela pouvait sauver une vie ?",
          "Les pays riches doivent-ils accueillir sans limite les réfugiés climatiques ?",
          "Donner un faux témoignage pour protéger un innocent, est-ce défendable ?",
          "Devrait-on expérimenter médicalement sur des prisonniers à vie ?",
          "Devrait-on imposer un âge maximum pour occuper des postes à responsabilité politique ?",
          "Serait-il juste de sélectionner qui a le droit de vivre en cas de catastrophe mondiale ?",
          "Serait-il acceptable d'espionner tous les citoyens pour éradiquer totalement la criminalité ?",
          "Est-ce que tout le monde a un prix ?",
          "Devrait-on interdire de faire des enfants si l'on vit dans une extrême pauvreté ?",
          "Pour ou contre la mise en place d'une identité numérique ?",
          "Peut-on condamner un artiste pour ses œuvres si celles-ci entraînent de la violence chez certains fans ?",
          "Devrait-on limiter la liberté d'acheter certaines technologies au grand public ?",
          "Si tu pouvais faire un crime sans être puni et ce crime ne serait plus jamais fait, lequel ça serait ?",
          "Si tu avais une roue avec 9 chances sur 10 de gagner 1 million mais 1 chance de mourir, la tournerais-tu ?",
          "Pour 1 million d'euros tu serais capable de regarder le film de ta vie avec tes parents ?",
          "Est-il égoïste de prioriser son propre bonheur avant celui des autres ?",
          "Comment tu définis le bien et le mal dans ta morale personnelle ?",
          "Penses-tu que les gens sont fondamentalement bons ou mauvais ?",
          "Est-ce qu'on peut être libre dans une société ?",
          "Comment tu acceptes les choses que tu ne peux pas changer ?",
          "Qu'est-ce que la liberté vraiment pour toi ?",
          "Y a-t-il une question existentielle qui te hante ?",
          "Crois-tu en une force supérieure, peu importe le nom qu'on lui donne ?",
          "Quel est le plus grand paradoxe de la vie selon toi ?",
          "Comment tu vois la relation entre le corps et l'esprit ?",
          "Qu'est-ce que l'identité ? Est-ce qu'elle change ou elle est fixe ?",
          "Penses-tu que la souffrance est nécessaire pour grandir ?",
          "Quel est ton plus grand regret amoureux ?",
          "Comment tu gères le désir sexuel au quotidien ?",
          "Est-ce que tu t'aimes ? Quel estime as-tu de toi ?",
          "Comment vas-tu (réellement) ?",
          "Quels sont les choses sur lesquelles tu dois travailler ?",
          "Si tu avais un pouvoir lequel tu voudrais ?",
          "Un homme qui pleure est faible ?",
          "C'est important pour une femme de garder son énergie féminine ?",
        ],
      },
    ],
  },
  {
    name: "Balance Ton Pote",
    slug: "balance-ton-pote",
    description: "La personne visée répond — honnêteté totale garantie !",
    icon: "🎤",
    colorMain: "#7C3AED",
    colorSecondary: "#A78BFA",
    order: 3,
    categories: [
      {
        name: "Classiques",
        slug: "classiques",
        icon: "😜",
        description: "Taquineries drôles sur habitudes/traits",
        order: 0,
        cards: [
          "Qui parle le plus sans rien dire ?",
          "Qui serait le dernier à survivre dans une forêt ?",
          "Qui est trop dramatique pour des trucs mineurs ?",
          "Qui oublie toujours ses affaires ?",
          "Qui ici pète des coutures mentales pour rien ?",
          "Qui est l'âme du groupe ?",
          "Qui ici nous ferait rire même dans les moments difficiles ?",
          "Qui est la personne la plus patiente du groupe ?",
          "Qui ici pense trop aux choses inutiles ?",
          "Qui est le plus spontané du groupe ?",
          "Qui prendrait la meilleure décision en cas de crise ?",
          "Qui a toujours une blague à raconter ?",
          "Qui est le plus organisé du groupe ?",
          "Qui a la meilleure mémoire ?",
          "Qui est le plus créatif ?",
          "Qui a le meilleur goût musical ?",
          "Qui ici a besoin de moins de sommeil ?",
          "Qui prendrait les meilleures photos du groupe ?",
          "Qui ici ferait le meilleur ami en période difficile ?",
          "Qui a le rire le plus contagieux ?",
          "Qui ici serait capable de faire un road trip spontané ?",
          "Qui nous ferait découvrir un nouvel endroit cool ?",
          "Qui a les meilleures histoires ?",
          "Qui serait le meilleur partenaire pour un projet ?",
          "Qui ici nous ferait rire quand on est sad ?",
          "Qui a la meilleure style vestimentaire ?",
          "Qui ici penserait en premier aux autres ?",
          "Qui serait le plus honnête avec vous ?",
          "Qui ici changerait le plus ta vie en positif ?",
          "Qui a le sourire le plus beau ?",
          "Qui ici dirait jamais de mal sur quelqu'un ?",
          "Qui serait le meilleur conseiller ?",
          "Qui ici a la plus grande empathie ?",
          "Qui serait ton meilleur ami dans 10 ans ?",
          "Qui ici te connaît vraiment le mieux ?",
          "Qui a la plus belle âme ?",
        ],
      },
      {
        name: "Règlements de Compte",
        slug: "reglements-compte",
        icon: "💣",
        description: "Accusations ludiques, \"tea\" drôle",
        order: 1,
        cards: [
          "C'est qui qui t'a le plus déçu cette année ?",
          "Tu penses quoi vraiment de la relation actuelle de quelqu'un ici ?",
          "C'est quoi l'erreur que quelqu'un ici répète souvent sans s'en rendre compte ?",
          "Si tu devais donner un conseil sincère à quelqu'un ici, ce serait lequel ?",
          "C'est quoi le truc que quelqu'un dit qu'il va faire mais ne fait jamais ?",
          "Qu'est-ce que quelqu'un ici pourrait améliorer dans sa façon de traiter les autres ?",
          "C'est quoi la décision de quelqu'un ici que tu n'aurais pas prise à sa place ?",
          "Si quelqu'un devait changer une chose en lui, ce serait quoi selon toi ?",
          "Qu'est-ce que quelqu'un ici mérite vraiment dans la vie qu'il n'a pas encore ?",
          "C'est quoi la vérité que tu veux dire à quelqu'un ici depuis longtemps ?",
          "Qui ferait la plus grande bêtise en confiance ?",
          "Qui ici serait capable de te trahir pour avancer ?",
          "Qui ici cache quelque chose d'important à tout le monde ?",
          "Qui ici ferait mentir pour te protéger ?",
          "Qui a besoin d'entendre un compliment sincère maintenant ?",
          "Qui ici ne demande jamais de l'aide même quand il en aurait besoin ?",
          "Qui ici juge les autres sans réaliser qu'il fait la même chose ?",
          "Qui ici a changé le plus cette année ?",
          "Qui ici mérite plus de reconnaissance ?",
          "Qui ici aurait besoin qu'on lui reparle directement au lieu de critiquer ?",
          "Qui ici ferait tout pour toi sans l'avouer ?",
          "Qui ici se fait du mal sans le réaliser ?",
          "Qui ici pense trop ce que les autres pensent ?",
          "Qui ici a les meilleures intentions mais la pire exécution ?",
          "Qui ici mérite une vraie conversation honnête ?",
          "Qui ici ignore complètement qu'il est inspirant ?",
          "Qui ici donne de mauvais conseils par bonne intentions ?",
          "Qui ici devrait arrêter de se dévaloriser ?",
          "Qui ici pense qu'on le juge mais personne ne le juge ?",
          "Qui ici ferait un meilleur leader si ça osait ?",
          "Qui ici prend pas assez soin de sa santé mentale ?",
          "Qui ici devrait voyager plus ?",
          "Qui ici devrait dire non plus souvent ?",
          "Qui ici a une addiction cachée ?",
          "Qui ici changerait la plus de mauvaises choses s'il pouvait se voir de dehors ?",
          "Qui ici est un secret keeper que nous ne soupçonnons pas ?",
        ],
      },
      {
        name: "Tabous et Limites",
        slug: "tabous-limites",
        icon: "🌙",
        description: "Secrets croquants, confessions fun",
        order: 2,
        cards: [
          "Qui de nous embrasserait le mieux ?",
          "Qui de nous serait le plus daring au lit ?",
          "Qui de nous a le meilleur physique selon vous ?",
          "Qui de nous serait le plus playful en intimité ?",
          "Qui de nous a la plus belle énergie sexuelle ?",
          "Qui de nous serait le plus tendre lors de l'intimité ?",
          "Qui de nous a le sourire le plus séducteur ?",
          "Qui de nous a le plus grand cœur du groupe ?",
          "Qui serait le meilleur ami quand ça va mal ?",
          "Qui penses-tu qu'il sous-estime sa propre force ?",
          "Qui ici serait le meilleur leader ?",
          "Qui a le plus grand potentiel caché ?",
          "Qui ici changerait vraiment tes priorités ?",
          "Qui de nous serait le plus fou en road trip ?",
          "Qui ici a les meilleur gènes ?",
          "Qui de nous prendrait les meilleurs selfies ensemble ?",
          "Qui ici pense trop à la place des autres ?",
          "Qui ici gagnerait un concours de beauté intérieure ?",
          "Qui ici faudrait qu'on encourage plus ?",
          "Qui de nous serait le partenaire idéal pour une relation ?",
          "Qui ici a l'aura la plus forte ?",
          "Qui de nous aurait le plus de succès en amour ?",
          "Qui ici changerait ta vision de l'amour ?",
          "Qui de nous ferait le meilleur parent ?",
          "Qui ici a la plus grande force intérieure ?",
          "Qui de nous aurait les meilleures aventures ?",
          "Qui ici mérite le plus d'être heureux ?",
          "Qui ici pense à tort ne pas être attirant ?",
          "Qui de nous a le plus beau rire ?",
          "Qui ici changerait ta vision des gens ?",
          "Qui de nous serait le plus fidèle en amour ?",
          "Qui ici a le plus d'impact sur toi ?",
          "Qui de nous ferait tourner les têtes en entrant quelque part ?",
          "Qui ici pense différemment et c'est génial ?",
          "Qui de nous inspire le plus de respect ?",
          "Qui ici te ferait devenir une meilleure version de toi ?",
          "Qui ici a l'énergie la plus contagieuse ?",
          "Qui de nous serait le plus surprenant au lit ?",
          "Qui ici devrait avoir plus confiance en son charme ?",
          "Qui de nous aurait le plus de secret fantasmes ?",
          "Qui ici rayonne vraiment en ce moment ?",
          "Qui de nous ferait le meilleur partenaire sexuel ?",
          "Qui ici a les meilleures intentions ?",
          "Qui de nous aurait la vie la plus excitante sexuellement ?",
          "Qui ici se sous-estime le plus ?",
          "Qui de nous mérite vraiment d'être apprécié comme il se doit ?",
          "Qui ici a changé ta vision de quelque chose d'important ?",
          "Qui de nous regarderait le mieux dans les yeux ?",
          "Qui ici a la meilleure énergie générale ?",
          "Qui de nous serait le plus séducteur naturellement ?",
        ],
      },
    ],
  },
];

async function main() {
  console.log("Seeding database (upsert mode — no data deleted)...");

  for (const gameData of seedData) {
    const { categories, ...gameFields } = gameData;

    const game = await prisma.game.upsert({
      where: { slug: gameFields.slug },
      update: { name: gameFields.name, description: gameFields.description, icon: gameFields.icon, colorMain: gameFields.colorMain, colorSecondary: gameFields.colorSecondary, order: gameFields.order },
      create: gameFields,
    });
    console.log(`  Game: ${game.name}`);

    for (const catData of categories) {
      const { cards, ...catFields } = catData;

      const category = await prisma.category.upsert({
        where: { gameId_slug: { gameId: game.id, slug: catFields.slug } },
        update: { name: catFields.name, description: catFields.description, icon: catFields.icon, order: catFields.order },
        create: { ...catFields, gameId: game.id },
      });

      for (let i = 0; i < cards.length; i++) {
        const existing = await prisma.card.findFirst({ where: { categoryId: category.id, text: cards[i] } });
        if (!existing) {
          await prisma.card.create({
            data: { categoryId: category.id, text: cards[i], active: true, order: i, tags: [] },
          });
        }
      }

      console.log(`    Category: ${category.name} (${cards.length} cards in seed)`);
    }

    const rules = defaultRules[game.slug];
    if (rules) {
      await prisma.gameRules.upsert({
        where: { gameId: game.id },
        update: { rules },
        create: { gameId: game.id, rules },
      });
    }
  }

  // New games: Mime Inversé + Devine le Mot + Dilemme
  for (const gameData of [...newGames, dilemmeGame]) {
    const { categories, rules, ...gameFields } = gameData as typeof gameData & { rules?: string | null };

    const game = await prisma.game.upsert({
      where: { slug: gameFields.slug },
      update: { name: gameFields.name, description: gameFields.description, icon: gameFields.icon, colorMain: gameFields.colorMain, colorSecondary: gameFields.colorSecondary, order: gameFields.order },
      create: gameFields,
    });
    console.log(`  Game: ${game.name}`);

    for (const catData of categories) {
      const { cards, difficulty, ...catFields } = catData as typeof catData & { difficulty?: string; cards: string[] };

      const category = await prisma.category.upsert({
        where: { gameId_slug: { gameId: game.id, slug: catFields.slug } },
        update: { name: catFields.name, description: catFields.description, icon: catFields.icon, order: catFields.order },
        create: { ...catFields, gameId: game.id },
      });

      for (let i = 0; i < cards.length; i++) {
        const existing = await prisma.card.findFirst({ where: { categoryId: category.id, text: cards[i] } });
        if (!existing) {
          await prisma.card.create({
            data: { categoryId: category.id, text: cards[i], difficulty: difficulty ?? null, active: true, order: i, tags: [] },
          });
        }
      }

      console.log(`    Category: ${category.name} (${cards.length} cards in seed)`);
    }

    if (rules) {
      await prisma.gameRules.upsert({
        where: { gameId: game.id },
        update: { rules },
        create: { gameId: game.id, rules },
      });
    }
  }

  const [games, categories, cards] = await Promise.all([
    prisma.game.count(),
    prisma.category.count(),
    prisma.card.count(),
  ]);

  console.log(`\nSeed complete: ${games} games, ${categories} categories, ${cards} cards`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
